### ISSUE TITLE
MISP to STIX2.1 converter doesn't ensure proper escaping in pattern string constants

### ISSUE THREAD

**Issue by chisholm** [MISP/misp-stix#2]
In many places, STIX patterns are created via direct concatenation or interpolation (inserting values directly into strings).  Where pattern string constants are concerned, this runs the risk of obtaining an invalid pattern due to improper escaping.  In string constants, single quotes and backslashes must be escaped.  Below is example content with a filename attribute which produces an error because the name includes a single quote.  It results in a pattern like `[file:name = 'eat at joe's']`, which is invalid.  (It is legal to have single quotes in filenames on Windows, for example.)  I saw there is some special case escaping when handling Windows registry keys (due to their backslashes).  For safety's sake, all values destined to be used as pattern string constants should probably be run through an escaping routine to ensure there are no errors.

```python
{
    'Org': {
        'name': 'Generator org',
        'uuid': '356e6202-335e-4eec-94f2-784a76e2b5aa'
    },
    'Orgc': {
        'name': 'Creator org',
        'uuid': '37374e80-1eee-4ee7-8e6a-c250ee7c59ed'
    },
    'date': '2021-05-26',
    'info': 'Test event',
    'publish_timestamp': '1622074905',
    'published': False,
    'timestamp': '1622074905',
    'uuid': '68ed9741-1f47-4883-a142-5ae50f298200',
    'Attribute': [
        {
            'category': 'Payload delivery',
            'last_seen': '2021-05-27T00:21:46.000000',
            'timestamp': '1622074905',
            'to_ids': True,
            'type': 'filename',
            'uuid': 'e688adbb-2b48-454c-a52f-ca4654c47b5f',
            'value': "eat at joe's"
        }
    ]
}
```

**Comment by chisholm** [comment]
I agree about `dev`.  Whether and how a textual value is escaped should depend on its usage context, not where it came from.

The reason you see an error with `"` is because you aren't allowed to escape double quotes in pattern string constants.  The [spec](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_bvkuhhujn5qm) says about escaping:

    The escape character is the backslash ('\' U+005c). Only the apostrophe or the backslash may follow,
    and in that case, the respective character is used for the sequence.

The key phrase is "only the apostrophe or backslash may follow".  Note that there are two levels of escaping you must deal with when writing Python code.  Python has certain rules regarding escaping, and STIX does also.  It is easy to get confused when you're dealing with multiple layers of escaping.  So:

* `\"` as Python code should not produce a validation error.  In a Python string literal (which contains a STIX pattern, in a string constant part of the contained pattern), that means just a double quote, which is fine unescaped inside a STIX pattern string constant.  In a STIX pattern string constant, that would be invalid, since double quotes are not allowed to follow backslashes.
* `\\"` as Python should produce a validation error, since that means a single backslash followed by a double quote, which is not a valid STIX pattern string constant.  As a STIX pattern string constant, it is okay since that is an escaped backslash followed by a (unescaped) double quote, and it is legal to escape backslashes in STIX pattern string constants.
* `\\\\"` should not produce a validation error in either case.  As a Python string literal, that means a double backslash followed by a double quote, which is a legal in a STIX pattern string constant since you're allowed to escape backslashes.  As a STIX pattern string constant, that is *two* escaped backslashes, followed by an *un*escaped double quote, which is also legal.

**Comment by chrisr3d** [comment]
Thank you for the clarification, I now understand better.

I merged `dev` into `main` so this issue should be fixed now
