### ISSUE TITLE
Feature Request: Handle MISPEvent when parsing

### ISSUE THREAD

**Issue by nyx0** [MISP/misp-stix#20]
### Is your feature request related to a problem? Please describe.

If I'm not mistaken misp-stix does not handle `MISPEvent` class. It would be nice to pass a `MISPEvent` to 

```python
from misp_stix_converter import MISPtoSTIX20Parser

parser20 = MISPtoSTIX20Parser()
parser20.parse_misp_event(event)  # event here is a MISPEvent
```

### Describe the solution you'd like

Handle MISPEvent class when parsing MISP events see `parse_misp_event` method.

### Describe alternatives you've considered

After retrieving a published event from MISP I did some modifications to the event (remove Objects, modifying comments...) 
When trying to give it to misp-stix parser I had to use do some tweaks for the STIX parser accepts the event.

```python
parser20 = MISPtoSTIX20Parser()    
for event in events:
  # Dump the class to json str, it recursively dump other classes as well
  # (like MISPObjects).

  # Painful tweak: force_timestamp for MISPEvent, MISPObject and MISPAttribute

  event.force_timestamp = True

  for obj in event.Object:
      obj.force_timestamp = True

  for attr in event.Attribute:
      attr.force_timestamp = True

  # Tweak: you have to give to stix parser a JSON, but `to_json()` return a str of JSON
  event_str = event.to_json()
  event_json = json.loads(event_str)

parser20.parse_misp_event(event_json)
```

### Additional context

The solution will probably require the `force_timestamp` method that @Rafiot added here https://github.com/MISP/PyMISP/commit/289ce47d64a79510bebc48178581b1853b7505df

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
Hey,

As the MISP <-> STIX conversion was a MISP core built-in feature, it was indeed missing the ability to take MISPEvents and other PyMISP content as input. The MISP to STIX export scripts always receive JSON inputs and I didn't think of any possible different input 

With the latest tagged version, it should be working with MISPEvents, the unit tests have been also extended to make sure both JSON and MISP formats are correctly supported.

Let me know if you face any further issue or edge case I missed
