### ISSUE TITLE
Bug: Incorrect conversion of attribute and event tags

### ISSUE THREAD

**Issue by kodeMunky** [MISP/misp-stix#41]
### Expected behavior

Please see https://github.com/MISP/MISP/issues/9095

### Actual behavior

Please see https://github.com/MISP/MISP/issues/9095

### Steps to reproduce

Please see https://github.com/MISP/MISP/issues/9095

### Version

v2.4.170

### Python version

3.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Correct link [https://github.com/MISP/MISP/issues/9095](https://github.com/MISP/MISP/issues/9095)

**Comment by kodeMunky** [comment]
Thanks @adulau , fixed the link in the bug report.

**Comment by chrisr3d** [comment]
Hey, I went through the issue in MISP/MISP#9095 and confirmed the guess I explained there, it was MISP passing "internal JSON format" with flattened fields with all the fields that are different from the standard MISP JSON format - like `AttributeTag` which should be `Tag`.

I pushed the following - https://github.com/MISP/MISP/commit/f35456baa0e9f6a845fbf0b005e4d94be1c74977 - to the `develop` branch, so it will be included in the next release.

I also tested with a medallion TAXII server - cf https://github.com/oasis-open/cti-taxii-server - and both the attributes and events tags are properly converted and pushed to TAXII
