### ISSUE TITLE
Adding a `--version` to `misp_stix_converter`

### ISSUE THREAD

**Issue by adulau** [MISP/misp-stix#66]
### Is your feature request related to a problem? Please describe.

Allowing user to know which version of misp-stix is installed and used when calling `misp-stix`

### Describe the solution you'd like

Adding a `--version` argument to print out the version number of the library.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
This is completed with [6243f82](https://github.com/MISP/misp-stix/commit/6243f8277c9173c8efe7a91ae4b45849855f0cbe)

**Comment by adulau** [comment]
Thank you!
